### ISSUE TITLE
Atualizar versão do Plone

### ISSUE THREAD

**Issue by ramiroluz** [interlegis/portalmodelo#6]
A versão do Plone 4 mais atual hoje é a 4.3.18.

Ao habilitar o complemento pas.plugins.ldap ocorre um erro reportado em:
  - https://github.com/plone/plone.app.workflow/issues/14
  - https://github.com/plone/Products.CMFPlone/issues/2053

Realizei um teste com o portalpadrao que possui a versão atualizada e o bug não ocorre.

https://github.com/plonegovbr/portal.buildout

Essa é a pinagem de complementos que usei no portal padrao:
```
# Integração com ldap
node = 0.9.20
node.ext.ldap = 1.0b7
node.ext.ugm = 0.9.9
pas.plugins.ldap = 1.5.3
yafowil = 2.2
yafowil.plone = 2.3.1
yafowil.widget.array = 1.4
yafowil.widget.dict = 1.6
yafowil.yaml = 1.2
```

**Comment by ramiroluz** [comment]
Testando com o Plone 4.3.19 + produtos do interlegis acontece um erro ao renderizar as páginas:

2019-12-05 10:01:26 ERROR plone.app.viewletmanager Error while rendering viewlet-manager=plone.portalfooter, viewlet=plone.footer
Traceback (most recent call last):
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/plone.app.viewletmanager-2.0.12-py2.7.egg/plone/app/viewletmanager/manager.py", line 106, in render
    html.append(viewlet.render())
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/simpleviewclass.py", line 44, in __call__
    return self.index(*args, **kw)
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/Zope2-2.13.29-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/Zope2-2.13.29-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 240, in __call__
    interpreter()
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 271, in __call__
    self.interpret(self.program)
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 858, in do_defineMacro
    self.interpret(macro)
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 531, in do_optTag_tal
    self.no_tag(stuff[-2], stuff[-1])
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 742, in do_insertStructure_tal
    structure = self.engine.evaluateStructure(expr)
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/Zope2-2.13.29-py2.7.egg/Products/PageTemplates/Expressions.py", line 218, in evaluateStructure
    text = super(ZopeContext, self).evaluateStructure(expr)
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/tales.py", line 696, in evaluate
    return expression(self)
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/pythonexpr.py", line 59, in __call__
    return eval(self._code, vars)
  File "<string>", line 1, in <module>
  File "/home/ramiro.luz/Plone/buildout-cache/eggs/Zope2-2.13.29-py2.7.egg/OFS/ObjectManager.py", line 783, in __getitem__
    raise KeyError, key
KeyError: 'footer-page'

**Comment by ramiroluz** [comment]
Aparentemente tem algum problema com javascript. Em formulários que possuem grids, o botão de adicionar nova linha não está funcionando corretamente. Exemplo do formulário de configuração do produto pas.plugins.ldap.
![Captura de tela de 2019-12-05 10-21-20](https://user-images.githubusercontent.com/293174/70238978-28a25480-1749-11ea-916a-c083a67d16f0.png)

**Comment by ramiroluz** [comment]
O produto interlegis.portalmodelo.ombudsman instala mas não aparece na lista de complementos.

**Comment by ramiroluz** [comment]
Criar uma página chamada footer-page elimina o erro. O erro vem do tema do portal que referência a footer-page. Entretanto esta não é criada pelos produtos em suas instalações.

> Testando com o Plone 4.3.19 + produtos do interlegis acontece um erro ao renderizar as páginas:
> 
> 2019-12-05 10:01:26 ERROR plone.app.viewletmanager Error while rendering viewlet-manager=plone.portalfooter, viewlet=plone.footer
> Traceback (most recent call last):
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/plone.app.viewletmanager-2.0.12-py2.7.egg/plone/app/viewletmanager/manager.py", line 106, in render
> html.append(viewlet.render())
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/simpleviewclass.py", line 44, in **call**
> return self.index(*args, **kw)
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/Zope2-2.13.29-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in **call**
> return self.im_func(im_self, *args, **kw)
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/Zope2-2.13.29-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in **call**
> sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
> strictinsert=0, sourceAnnotations=sourceAnnotations
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 240, in **call**
> interpreter()
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 271, in **call**
> self.interpret(self.program)
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
> handlers[opcode](self, args)
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 858, in do_defineMacro
> self.interpret(macro)
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
> handlers[opcode](self, args)
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 531, in do_optTag_tal
> self.no_tag(stuff[-2], stuff[-1])
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
> self.interpret(program)
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
> handlers[opcode](self, args)
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 742, in do_insertStructure_tal
> structure = self.engine.evaluateStructure(expr)
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/Zope2-2.13.29-py2.7.egg/Products/PageTemplates/Expressions.py", line 218, in evaluateStructure
> text = super(ZopeContext, self).evaluateStructure(expr)
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/tales.py", line 696, in evaluate
> return expression(self)
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/pythonexpr.py", line 59, in **call**
> return eval(self._code, vars)
> File "", line 1, in
> File "/home/ramiro.luz/Plone/buildout-cache/eggs/Zope2-2.13.29-py2.7.egg/OFS/ObjectManager.py", line 783, in **getitem**
> raise KeyError, key
> KeyError: 'footer-page'
